local t = Def.ActorFrame{
  Def.ActorFrame{
    InitCommand=cmd(addy,183;addx,66;);
    LoadActor("ki.png")..{
      InitCommand=cmd(addx,-171);
    };
    LoadActor("tsu.png")..{
      InitCommand=cmd(addx,-150;addy,4);
    };
    LoadActor("to.png")..{
      InitCommand=cmd(addx,-128);
    };
    LoadActor("odori.png")..{
      InitCommand=cmd(addx,-105;addy,1);
    };
    LoadActor("wa.png")..{
      InitCommand=cmd(addx,-79;addy,1);
    };
    LoadActor("ru.png")..{
      InitCommand=cmd(addx,-55;addy,1);
    };
    LoadActor("!.png")..{
      InitCommand=cmd(addx,-37;addy,1);
    };
    LoadActor("ki kanji.png")..{
      InitCommand=cmd(addx,-16);
    };
    LoadActor("kei.png")..{
      InitCommand=cmd(addx,11);
    };
    LoadActor("ni.png")..{
      InitCommand=cmd(addx,38;addy,1);
    };
    LoadActor("da.png")..{
      InitCommand=cmd(addx,62;addy,-1);
    };
    LoadActor("n.png")..{
      InitCommand=cmd(addx,86;addy,1);
    };
    LoadActor("shi.png")..{
      InitCommand=cmd(addx,111;addy,1);
    };
    LoadActor("n.png")..{
      InitCommand=cmd(addx,134;addy,1);
    };
    LoadActor("gu.png")..{
      InitCommand=cmd(addx,158;addy,-1);
    };
    LoadActor("!.png")..{
      InitCommand=cmd(addx,177;addy,1);
    };
  };
  Def.ActorFrame{
    InitCommand=cmd(addy,183;addx,66);
    GainFocusCommand=cmd(finishtweening;sleep,0.8;queuecommand,"Anim";sleep,2;queuecommand,"GainFocus");
    LoseFocusCommand=cmd(finishtweening;);
    LoadActor("ki.png")..{
      InitCommand=cmd(addx,-171;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.05;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("tsu.png")..{
      InitCommand=cmd(addx,-150;addy,4;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.15;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("to.png")..{
      InitCommand=cmd(addx,-128;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.2;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("odori.png")..{
      InitCommand=cmd(addx,-105;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.25;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("wa.png")..{
      InitCommand=cmd(addx,-79;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.3;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("ru.png")..{
      InitCommand=cmd(addx,-55;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.35;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("!.png")..{
      InitCommand=cmd(addx,-37;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.4;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("ki kanji.png")..{
      InitCommand=cmd(addx,-16;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.45;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("kei.png")..{
      InitCommand=cmd(addx,11;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.5;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("ni.png")..{
      InitCommand=cmd(addx,38;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,.55;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("da.png")..{
      InitCommand=cmd(addx,62;addy,-1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,.6;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("n.png")..{
      InitCommand=cmd(addx,86;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,.65;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("shi.png")..{
      InitCommand=cmd(addx,111;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.7;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("n.png")..{
      InitCommand=cmd(addx,134;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.75;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("gu.png")..{
      InitCommand=cmd(addx,158;addy,-1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.8;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
    LoadActor("!.png")..{
      InitCommand=cmd(addx,177;addy,1;blend,Blend.Add;diffusealpha,0);
      AnimCommand=cmd(diffusealpha,0;zoom,1;sleep,0.85;linear,0.005;zoom,1.4;diffusealpha,0.5;sleep,0.2;linear,0.005;diffusealpha,0);
    };
  };
};

return t;
