local t = Def.ActorFrame{
  InitCommand=cmd(addy,183;addx,80;);
  LoadActor("full base");
  Def.ActorFrame{
    Def.Quad{
      InitCommand=cmd(x,-200;setsize,100,36;MaskSource,true);
      GainFocusCommand=cmd(finishtweening;x,-300;sleep,0.8;queuecommand,"Anim");
      AnimCommand=cmd(finishtweening;x,-300;linear,0.4;x,300;sleep,2.4;queuecommand,"Anim");
      LoseFocusCommand=cmd(finishtweening;);
    };
    Def.ActorFrame{
      InitCommand=cmd(MaskDest;ztestmode,"ZTestMode_WriteOnFail");
      LoadActor("d.png")..{
        InitCommand=cmd(zoom,1.3;addx,-151;blend,Blend.Add;);
      };
      LoadActor("d.png")..{
        InitCommand=cmd(zoom,1.3;addx,-129;blend,Blend.Add;);
      };
      LoadActor("r.png")..{
        InitCommand=cmd(zoom,1.3;addx,-106;blend,Blend.Add;);
      };
      LoadActor("1.png")..{
        InitCommand=cmd(zoom,1.3;addx,-82;addy,1;blend,Blend.Add;);
      };
      LoadActor("2.png")..{
        InitCommand=cmd(zoom,1.3;addx,-58;addy,2;blend,Blend.Add;);
      };
      LoadActor("3.png")..{
        InitCommand=cmd(zoom,1.3;addx,-32;addy,1;blend,Blend.Add;);
      };
      LoadActor("4.png")..{
        InitCommand=cmd(zoom,1.3;addx,-5;addy,1;blend,Blend.Add;);
      };
      LoadActor("5.png")..{
        InitCommand=cmd(zoom,1.3;addx,21;addy,1;blend,Blend.Add;);
      };
      LoadActor("6.png")..{
        InitCommand=cmd(zoom,1.3;addx,50;addy,-1;blend,Blend.Add;);
      };
      LoadActor("7.png")..{
        InitCommand=cmd(zoom,1.3;addx,77;addy,1;blend,Blend.Add;);
      };
      LoadActor("8.png")..{
        InitCommand=cmd(zoom,1.3;addx,101;addy,0;blend,Blend.Add;);
      };
      LoadActor("9.png")..{
        InitCommand=cmd(zoom,1.3;addx,124;addy,0;blend,Blend.Add;);
      };
      LoadActor("!.png")..{
        InitCommand=cmd(zoom,1.3;addx,142;addy,1;blend,Blend.Add;);
      };
      LoadActor("!.png")..{
        InitCommand=cmd(zoom,1.3;addx,157;addy,1;blend,Blend.Add;);
      };
    };
  };
};

return t;
