local t = Def.ActorFrame{
  InitCommand=cmd(addy,183;addx,66;);
  LoadActor("full base");
  Def.ActorFrame{
    Def.Quad{
      InitCommand=cmd(x,-200;setsize,100,36;MaskSource,true);
      GainFocusCommand=cmd(finishtweening;x,-300;sleep,0.8;queuecommand,"Anim");
      AnimCommand=cmd(finishtweening;x,-300;linear,0.4;x,300;sleep,2.4;queuecommand,"Anim");
      LoseFocusCommand=cmd(finishtweening;);
    };
    Def.ActorFrame{
      InitCommand=cmd(MaskDest;ztestmode,"ZTestMode_WriteOnFail");
      LoadActor("ki.png")..{
        InitCommand=cmd(zoom,1.3;addx,-171;blend,Blend.Add;);
      };
      LoadActor("tsu.png")..{
        InitCommand=cmd(zoom,1.3;addx,-150;addy,4;blend,Blend.Add;);
      };
      LoadActor("to.png")..{
        InitCommand=cmd(zoom,1.3;addx,-128;blend,Blend.Add;);
      };
      LoadActor("odori.png")..{
        InitCommand=cmd(zoom,1.3;addx,-105;addy,1;blend,Blend.Add;);
      };
      LoadActor("wa.png")..{
        InitCommand=cmd(zoom,1.3;addx,-79;addy,1;blend,Blend.Add;);
      };
      LoadActor("ru.png")..{
        InitCommand=cmd(zoom,1.3;addx,-55;addy,1;blend,Blend.Add;);
      };
      LoadActor("!.png")..{
        InitCommand=cmd(zoom,1.3;addx,-37;addy,1;blend,Blend.Add;);
      };
      LoadActor("ki kanji.png")..{
        InitCommand=cmd(zoom,1.3;addx,-16;blend,Blend.Add;);
      };
      LoadActor("kei.png")..{
        InitCommand=cmd(zoom,1.3;addx,11;blend,Blend.Add;);
      };
      LoadActor("ni.png")..{
        InitCommand=cmd(zoom,1.3;addx,38;addy,1;blend,Blend.Add;);
      };
      LoadActor("da.png")..{
        InitCommand=cmd(zoom,1.3;addx,62;addy,-1;blend,Blend.Add;);
      };
      LoadActor("n.png")..{
        InitCommand=cmd(zoom,1.3;addx,86;addy,1;blend,Blend.Add;);
      };
      LoadActor("shi.png")..{
        InitCommand=cmd(zoom,1.3;addx,111;addy,1;blend,Blend.Add;);
      };
      LoadActor("n.png")..{
        InitCommand=cmd(zoom,1.3;addx,134;addy,1;blend,Blend.Add;);
      };
      LoadActor("gu.png")..{
        InitCommand=cmd(zoom,1.3;addx,158;addy,-1;blend,Blend.Add;);
      };
      LoadActor("!.png")..{
        InitCommand=cmd(zoom,1.3;addx,177;addy,1;blend,Blend.Add;);
      };
    };
  };
};

return t;
